#FROM jeffreymanning/centos-base
# this is geared towards spark environment
FROM jeffreymanning/spark-base
LABEL maintainer="JWM" \
      vendor="MITRE Corp" \
      version="3.4" \
      release="0" \
      summary="MITRE's base Spark-R image - 3.4.x/2.1.1 API node" \
      description="Centos7, Spark, R typically used for API nodes" \
### Required labels above - recommended below
      io.k8s.description="Centos, Spark-R base API node image" \
      io.k8s.display-name="centos, Spark-R API node image" \
      io.openshift.expose-services="SparkR-base" \
      io.openshift.tags="centos7,Spark,R,java,maven"

USER root

#install the basic packages, must install sudo - some downstream cf6c240acc517onsumers cannot run as root
RUN yum clean all && \
###  R lives in the epel-release, epel installed in spark-base
# # helpers for R package downloading: libcurl libcurl-devel openssl openssl-devel gnutls gnutls-devel
    INSTALL_PKGS="libicu libicu-devel blas blas-devel lapack lapack-devel libxml2 libxml2-devel texinfo texinfo-tex texlive-epsf \
                   gnutls gnutls-devel \
                   R R-core R-core-devel R-devel" && \
    yum install -y --setopt=tsflags=nodocs ${INSTALL_PKGS} && \
    yum groupinstall "Development Tools" && \
    yum -y update && \
    yum clean all -y && \
    rm -rf /var/cache/yum

## alternatively.. using centos
# http://mirror.centos.org/centos/7/os/x86_64/Packages/<package>
# centos/7 is the latest version... but requires managing the version stamps
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/texinfo-5.1-4.el7.x86_64.rpm disable_gpg_check=yes state=present
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/texinfo-tex-5.1-4.el7.x86_64.rpm disable_gpg_check=yes state=present
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/blas-3.4.2-5.el7.x86_64.rpm disable_gpg_check=yes state=present
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/blas-devel-3.4.2-5.el7.x86_64.rpm disable_gpg_check=yes state=present
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/lapack-3.4.2-5.el7.x86_64.rpm disable_gpg_check=yes state=present
#RUN yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/lapack-devel-3.4.2-5.el7.x86_64.rpm disable_gpg_check=yes state=present

## configure
#RUN mkdir -p /etc/R && \
#    touch /etc/R/Rprofile.site && \
#    touch /etc/littler.r && \
#    echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site && \
#    echo 'source("/etc/R/Rprofile.site")' >> /etc/littler.r && \
#    echo ln -s /usr/share/doc/littler/examples/install.r /usr/local/bin/install.r && \
#    ln -s /usr/share/doc/littler/examples/install2.r /usr/local/bin/install2.r  && \
#    ln -s /usr/share/doc/littler/examples/installGithub.r /usr/local/bin/installGithub.r && \
#    ln -s /usr/share/doc/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r

### R is installed into /usr/local/lib/R
## Set a default user. Available via runtime flag `--user docker`
## Add user to 'staff' group, granting them write privileges to /usr/local/lib/R/site.library
## User should also have & own a home directory (for rstudio or linked volumes to work properly).
RUN groupadd staff
#RUN useradd docker \
#	&& chown docker:docker /home/docker \
#    && usermod -aG staff docker

## Add a library directory (for user-installed packages)
RUN mkdir -p /usr/local/lib/R/site-library && \
    chown root:staff /usr/local/lib/R/site-library && \
    chmod g+wx /usr/local/lib/R/site-library

# default package insatalltion to docker location...  will be lost if shutown
ARG R_STUDIO_LIB_SITE=/usr/local/lib/R/site-library

# setup some environment stuff - https://cran.r-project.org/mirrors.html
# https://cran.cnr.berkeley.edu/
# http://cran.stat.ucla.edu/
# http://lib.stat.cmu.edu/R/CRAN/
ARG CRAN_REPO=http://lib.stat.cmu.edu/R/CRAN/
ARG BIO_REPO=https://bioconductor.org/

## Fix library path to confirm (R then .libPaths())
# "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/share/R/library:/usr/lib64/R/library'}"
ENV R_HOME=/usr/lib64/R
ENV R_LIBS_USER=${R_STUDIO_LIB_SITE}
ENV R_LIBS=${R_LIBS_USER}:/usr/share/R/library:/usr/lib64/R/library
RUN echo 'options(repos = c(CRAN = "${CRAN_REPO}"), download.file.method = "libcurl")' >> ${R_HOME}/etc/Rprofile.site
RUN echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> ${R_HOME}/etc/Renviron

# miniml [packages required to build Spark R/knitr interpreter]
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('evaluate'), Sys.getenv('R_LIBS_USER'), repos='${CRAN_REPO}')"
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('base64enc'), Sys.getenv('R_LIBS_USER'), repos='${CRAN_REPO}')"
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('knitr'), Sys.getenv('R_LIBS_USER'), repos='${CRAN_REPO}')"
#RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('libcurl'), repos='${CRAN_REPO}')"
#RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('libcurl-devel'), repos='${CRAN_REPO}')"
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('curl'), repos='${CRAN_REPO}')"
#RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('RCurl'), repos='${CRAN_REPO}')"
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs=c('devtools'), Sys.getenv('R_LIBS_USER'), repos='${CRAN_REPO}')"
RUN /usr/bin/Rscript --slave --no-save --no-restore-history -e "library('devtools'); devtools::install_github('IRkernel/repr')"

# get off root, move to default
USER default

#### Define default command.
# R causes backoff loop failures - default to centos7-base
#CMD ["R"]


